services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/build
      - /app/.gradle
    restart: always
    command: java -jar ./build/libs/festino-main-0.0.1-SNAPSHOT.jar
